"""
app/schemas/eda.py — Pydantic response model for POST /api/eda.

Models:
  EDAResponse — Response body returned by the EDA endpoint:
                  metrics — flat list of Metric objects (label/value pairs)
                            covering shape stats, missing values, outlier counts,
                            correlation info, and target class stats depending on
                            which analyses were requested.
                  plots   — list of base64-encoded PNG data URIs generated by
                            eda_engine.py (distribution histograms and/or
                            correlation heatmap). Empty list if no plot analyses
                            were requested.
"""
from pydantic import BaseModel
from .upload import Metric


class EDAResponse(BaseModel):
    metrics: list[Metric]
    plots: list[str] = []
